/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rnkoaa.secret.plugin

import org.gradle.api.provider.Property

/**
 * A simple 'hello world' plugin.
 */
interface SecretPluginExtension {
    var message: Property<String>?
}