/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rnkoaa.secret.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class SecretPlugin: Plugin<Project> {
    override fun apply(project: Project) {
//        val extension = project.extensions.configure<SecretPluginExtension>("secret", SecretPluginExtension::class)
        val extension = project.extensions.create("secrets", SecretPluginExtension::class.java)
//        val extension = project.extensions.create<SecretPluginExtension>("greeting")
        // Register a task
        project.tasks.register("secret") { task ->
            task.doLast {
                val message = extension.message?.get() ?: "hello"
                println(message)
            }
        }
    }
}
